title: Andy Eschbacher
author: Andy Eschbacher
description: Personal website of Andy Eschbacher
long_description: Andy Ash Tree Brook. Dad, husband, explorer. Fifty states visited. Former mathematical physicist who loves solving problems with Python, SQL, and math. Usually dreaming of my next bike or hike. Currently working as a spatial data scientst at <a href="https://carto.com/">CARTO</a>.
email: andy.eschbacher@gmail.com
theme:
twitter_username: MrEPhysics
github_username: andy-esch 
linkedin_username: andyeschbacher
google_analytics: UA-102765591-1
markdown: kramdown
