title: Andy Eschbacher
author: Andy Eschbacher
description: Personal website of Andy Eschbacher
long_description: Andy Ash Tree Brook. Dad, husband, explorer. Fifty states visited. Former mathematical physicist who loves solving problems with Python, SQL, and math. Usually dreaming of my next bike or hike. Currently working as lead geospatial scientist at <a href="https://ipsos.com/">Ipsos</a> in the Washington DC area.
email: andyesch@protonmail.com
theme: jekyll-theme-minimal
twitter_username: MrEPhysics
github_username: andy-esch 
linkedin_username: andyeschbacher
google_analytics: UA-102765591-1
markdown: kramdown
highlighter: rouge
